### ISSUE TITLE
sentry_events_total window to small

### ISSUE THREAD

**Issue by bkk-bcd** [italux/sentry-prometheus-exporter#54]
**Describe the bug**
The window used to retrieve `sentry_events_total` is too small making it very easy to send up with lots of gaps in metrics data during slow hours/weekends/etc.

**To Reproduce**

I enabled debugging in the exporter and noticed the following:

```
/api/0/projects/xx/production/stats/?stat=received&since=1651413962.111302&until=1651413962.111314
```

If you performa query in prometheus you'll see gaps:

```
sentry_events_total{project_slug=~"production|uat",stat="received"}[60m]

0 @1651415150.719
0 @1651415450.719
0 @1651415750.719
0 @1651416050.719
0 @1651416350.719
22 @1651416650.719
0 @1651416950.718
0 @1651417250.718
0 @1651417550.718
0 @1651417850.718
0 @1651418150.718
4 @1651418450.718
```

Note I'm using the recommended scraper settings:

```
scrape_configs:
  - job_name: 'sentry_exporter'
    static_configs:
    - targets: ['sentry-exporter:9790']
    scrape_interval: 5m
    scrape_timeout: 4m
```

**Expected behavior**
Counter values that reflect the actual events received...

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
